### ISSUE TITLE
模型下载问题

### ISSUE THREAD

**Issue by Nicola-Zhang** [Sense-GVT/SNCSE#2]
您好，十分感谢您的分享！请问您的checkpoint有其他链接吗？百度云下载太慢了！谢谢！

**Comment by phoenixsecularbird** [comment]
您好！谢谢关注我们的工作。年后我们会上传谷歌云，现在您可以在百度网盘里设置提速模式，个人亲测有效🤗🤗🤗

**Comment by phoenixsecularbird** [comment]
您好！我们的checkpoint文件已经上传谷歌云，地址为https://drive.google.com/drive/folders/1w2srzbtTMLlaxUx-7ETV9vQWdw_6lVuN?usp=sharing
